#!/usr/bin/env bash

set -e

screenname="$1"
shift

if [ -z "$SCREEN_LOG_DIR" ]; then
  logfile="$(readlink -f "$screenname")"
else
  logfile="$SCREEN_LOG_DIR/$screenname"
fi

if [ -e "$logfile" ]; then
  echo "Warning: $logfile already exists" 1>&2
  mv "$logfile" "$logfile".bak
fi

screenrc="`mktemp`"

echo "logfile $logfile" > "$screenrc"

echo "Starting screen $screenname, conf file $screenrc:"
cat "$screenrc"
echo ''
echo "args: $@"

screen -c "$screenrc" -L -S "$screenname" "$@"
